### ISSUE TITLE
Some question about speed up

### ISSUE THREAD

**Issue by wangqiim** [Booooooooooo/CSD#12]
Thanks for your job. It help me a lot. I have some question about speed up to ask.

![image](https://user-images.githubusercontent.com/59993523/148199328-2c20afba-d2ce-4362-8fa9-c2b50fe785d9.png)

in rw= 0.5x. in figure (a) .Because input channel and output channel will reduce by half. So the parameters only use 1/4 is easy to understand. But in figure (b), Why the speed time only reduce by half (not 1/4)? Can you explain a little bit? :)

**Comment by buptlj** [comment]
很好理解啊，速度和参数量不是完全成比例的，随便用个网络测试一下就知道了。

**Comment by wangqiim** [comment]
> 很好理解啊，速度和参数量不是完全成比例的，随便用个网络测试一下就知道了。

我上面的意思不是说参数量和速度的关系哈，实际上channel split以后的flops降低的比例和参数量一样（原问题应该加一句flops减低为1/4）。因此，我把论文里的channel split操作提出来，单独测试时虽然加速比达不到4但是也是能有2~3的，觉得1.39太低了，也许是我channel split的时候漏了论文里的什么细节

**Comment by buptlj** [comment]
> > 很好理解啊，速度和参数量不是完全成比例的，随便用个网络测试一下就知道了。
> 
> 我上面的意思不是说参数量和速度的关系哈，实际上channel split以后的flops降低的比例和参数量一样。因此，我把论文里的channel split操作提出来，单独测试时虽然加速比达不到4但是也是能有2~3的，我觉得1.39太低了，也许是我channel split的时候漏了论文里的什么细节

那具体就不清楚了，不过也可能和硬件有关，不同硬件对不同算子的优化也不一样。
