### ISSUE TITLE
Is it only works on existing models, or eventually it outputs a pertained model based on a reference one? 

### ISSUE THREAD

**Issue by roimulia2** [Booooooooooo/CSD#3]
Hey there! looking very interesting. 

Is it only works on existing models, or eventually it outputs a pertained model based on a reference one? 

Roi

**Comment by Booooooooooo** [comment]
Thank you for reaching out.
I’m sorry that I don’t quite understand your question. Using our method to compress existing models will get a pretrained model based on the reference model. You could also apply our method to compress new models. But still, it is a compression method so you have to specify which model you want to compress.
