### ISSUE TITLE
the code is different to the paper

### ISSUE THREAD

**Issue by songyonger** [Booooooooooo/CSD#5]
Your paper use EDSR，but the code seems is RDN

**Comment by Booooooooooo** [comment]
Sorry, I don't quite understand your problem. Which code are you referring to? Our model/edsr.py is based on https://github.com/sanghyun-son/EDSR-PyTorch/blob/master/src/model/edsr.py. We do not use feature fusion.

**Comment by songyonger** [comment]
请问carn.py里为什么会有通道维度上的拼接操作呢？(torch.cat)

**Comment by songyonger** [comment]
对不起，看错了，抱歉
