### ISSUE TITLE
CL negtive sample question

### ISSUE THREAD

**Issue by wangqiim** [Booooooooooo/CSD#6]
Thanks for sharing your code online! I have some question about construting negtive sample. In [`CSD/PyTorch version/trainer/slim_contrast_trainer.py#L100`]
```python
bic_sample = lr[torch.randperm(self.neg_num), :, :, :]
```
(https://github.com/Booooooooooo/CSD/blob/main/PyTorch%20version/trainer/slim_contrast_trainer.py#L100). I think some negtive sample actually is a positive sample. For example, Why not set batchsize = old_batch_size+neg_num. In each iterate, use old_batch_size sample constructing sample+postive samples, and use the remaining neg_num samples as the negative samples

**Comment by Booooooooooo** [comment]
Thanks for your interest. We've also considered the way you described. However, due to implementation convenience and the memory overhead, we simplified the process.
